### ISSUE TITLE
dnsbrute

### ISSUE THREAD

**Issue by LockGit** [chuhades/dnsbrute#2]
➜  dnsbrute git:(master) dnsbrute
zsh: command not found: dnsbrute

please ls -l dnsbrute
cat dnsbrute

**Comment by chu1337** [comment]
compile it first plz.

if you want execute by `dnsbrute`, add the binary's directory path to your `PATH` first.

you should learn about linux first : )

**Comment by LockGit** [comment]
...
➜  dns git:(master) ✗ cat api.go
"github.com/astaxie/beego/httplib"

...
....

➜ dnsbrute git:(master) dnsbrute
zsh: command not found: dnsbrute

Of course can add  path to .zshrc file, Just export PATH ,

only tell you the document imperfect
