### ISSUE TITLE
在没有NO NS Record情况下终止。

### ISSUE THREAD

**Issue by Aroundight** [chuhades/dnsbrute#4]
例如 xxxx.com 的ns记录为空时，则直接退出程序。这种情况太常见了，推荐在这时添加几大主dns服务器。
即修改pandns.go中

func SetAuthoritativeDNSServers() error {
	if analyzeAuthoritativeDNSServersLimit == 0 {
		authoritativeDNSServers = append(authoritativeDNSServers, "8.8.8.8:53")
		authoritativeDNSServers = append(authoritativeDNSServers, "119.29.29.29:53")
		authoritativeDNSServers = append(authoritativeDNSServers, "223.5.5.5:53")
		authoritativeDNSServers = append(authoritativeDNSServers, "223.6.6.6:53")
		authoritativeDNSServers = append(authoritativeDNSServers, "114.114.114.114:53")
		fmt.Sprintf("%s: NO NS Record", rootDomain)
		return nil
	}
.
.
.

再优化的话就是对 有ns的服务器和常用ns服务器 进行 延迟检测，选择最优的ns服务器进行爆破

**Comment by Aroundight** [comment]
还有程序并发能力很强，可以充分发挥网络性能，但是也会造成差的网络retry随便都超过3次，造成结果不准确。线程来限制速率的方式不够可控。不知道后期能不能改成 masscan和zmap的 限制 每分钟最大发包数这样。

**Comment by chu1337** [comment]
使用权威dns是有我的考虑的，可以看[http://sh3ll.me/archives/201704041222.txt](http://sh3ll.me/archives/201704041222.txt)，最后一条。

上一个小版本使用的是第三方dns。如果域名没有配置ns服务器，那他是怎样解析的呢，如果那样他应该不会有子域名的吧。

第二个问题，本来我是想用发包数的：），但是发包数不是很好理解，于是就用这个方案了，使用线程+间隔时间的方式。

后面有时间可能会增加些别的配置项，比如发包、是否轮寻子域名等。

感谢：）

**Comment by chu1337** [comment]
线程+时间间隔其实可以等同于发包数呀，但是也对，感觉不优雅。

**Comment by Aroundight** [comment]
有子域名，例如大家喜欢的 bilibili.com ，直接查 bilibili.com 是没有ns记录的

**Comment by Aroundight** [comment]
选择第三方dns时候的确需要做判断，我最上面那样写，会造成部分效率低下。但是在没ns记录情况下，也不为是一个选择，所以写在 ns记录判断无的分支里。

**Comment by chu1337** [comment]
找到原因了，bilibili是走的soa，并不是没有ns记录。这点以前确实不了解，学习了。

```
➜  chuhades/dnsbrute git:(master) dig soa bilibili.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> soa bilibili.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5911
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;bilibili.com.			IN	SOA

;; ANSWER SECTION:
bilibili.com.		123	IN	SOA	ns1.hdslb.net. root.hdslb.net. 5351604 3600 180 1209600 180

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sun May 21 15:14:07 CST 2017
;; MSG SIZE  rcvd: 95

➜  chuhades/dnsbrute git:(master) dig @ns1.hdslb.net ns bilibili.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @ns1.hdslb.net ns bilibili.com
; (4 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37523
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;bilibili.com.			IN	NS

;; AUTHORITY SECTION:
bilibili.com.		180	IN	SOA	ns1.hdslb.net. root.hdslb.net. 22281604 3600 180 1209600 180

;; Query time: 80 msec
;; SERVER: 27.148.248.70#53(27.148.248.70)
;; WHEN: Sun May 21 15:14:20 CST 2017
;; MSG SIZE  rcvd: 95

➜  chuhades/dnsbrute git:(master) dig @ns1.hdslb.net www.bilibili.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @ns1.hdslb.net www.bilibili.com
; (4 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56257
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;www.bilibili.com.		IN	A

;; ANSWER SECTION:
www.bilibili.com.	300	IN	CNAME	bilibili.hdslb.net.
bilibili.hdslb.net.	180	IN	A	219.144.79.7

;; Query time: 34 msec
;; SERVER: 110.76.40.240#53(110.76.40.240)
;; WHEN: Sun May 21 15:14:29 CST 2017
;; MSG SIZE  rcvd: 93
```

- https://zhidao.baidu.com/question/385509462.html
- https://www.zhihu.com/question/40028869
- http://bbs.51cto.com/thread-908637-1.html

**Comment by chu1337** [comment]
更新了新版本，不再采用权威ns 服务器的方式（可自己指定ns server），解决了此问题。

```
➜  dnsbrute wc -l bilibili.com.csv
      66 bilibili.com.csv
```
